#!/usr/bin/lua
--[[
  *******************************************************************
  **                                                               **
  **                   Lua 6502 Assembler                          **
  **                                                               **
  **                 (?) 2022 by A.C.M. on                         **
  **                Deadsoft Development Corp.                     **
  **                                                               **
  *******************************************************************
]]--

ass = {}
ass.source = {}                                                                          -- Source-Code
ass.code = {}                                                                            -- Working Code
ass.labels = {}                                                                          -- Table of Labels
ass.lib = {}                                                                             -- Function-Lib for the Assembler
ass.lib.parse = {}                                                                       -- The Steps to Pass
ass.registered_command = {}                                                              -- Command the Assembler knows
ass.error = {}                                                                           -- Reports with Number. 0 = Ok.
ass.pre = {}                                                                             -- Save the presigns
ass.post = {}                                                                            -- Save the postsigns
ass.mode = {}                                                                            -- Mode for the command
ass.adress = {}                                                                          -- Adress of the line
ass.start = 0                                                                            -- Current Base to Calc, Command *
ass.last = 0                                                                             -- Codeend
ass.pc = 0                                                                               -- Current Adress of the Processorpointer
ass.set_base = false                                                                     -- Is start or base (*) already set?
ass.filename = ... or ""                                                                 -- Filename as Argument
ass.objectname = ""                                                                      -- Programm Filename
ass.debug = true                                                                         -- Error-Flag, true = all ok
ass.current_line = 0                                                                     -- Current line to process

ass.version = 1
ass.revision = 0

ass.pass = 1                                                                             -- Current Assembler-Pass
ass.base = 0

local a = ass

if((a.filenname == "") or (not a.filename)) then 
    print("Usage: lua_ass <Filename>")
    print("Error, no filename given")
    os.exit()
    
end -- if(a.filename

a.objectname = a.filename:match("[^%.*]+") .. ".prg"

dofile("log.lua")
dofile("lib.lua")
dofile("parser_6502.lua")

local l = logger


if(a.debug) then
  l.filename = a.filename .. ".log"
  l.open()

end -- if(a.debug)

l.log("Try to load commands.")
local commands = {
                    -- Special Assembler-Command
                    "cmd_do_nothing.lua",
                    "cmd_calc_parameter.lua",
                    "cmd_calc_branch.lua",
                    "cmd_turn_value.lua",
                    "cmd_star.lua",
                    "cmd_label.lua",
                    "cmd_dc.lua",
                    "cmd_calc_mode.lua",
                    
                    -- Official Assembler-Commands
                    "cmd_lda.lua",
                    "cmd_sta.lua",
                    "cmd_and.lua",
                    "cmd_eor.lua",
                    "cmd_ora.lua",
                    "cmd_adc.lua",
                    "cmd_sbc.lua",
                    "cmd_cmp.lua",
                    "cmd_cpx.lua",
                    "cmd_cpy.lua",
                    "cmd_dec.lua",
                    "cmd_inc.lua",
                    "cmd_rol.lua",
                    "cmd_asl.lua",
                    "cmd_lsr.lua",
                    "cmd_ror.lua",
                    "cmd_ldx.lua",
                    "cmd_ldy.lua",
                    "cmd_stx.lua",
                    "cmd_sty.lua",
                    "cmd_jmp.lua",
                    "cmd_jsr.lua",
                    "cmd_bit.lua",
                    "cmd_dex.lua",
                    "cmd_dey.lua",
                    "cmd_inx.lua",
                    "cmd_iny.lua",
                    "cmd_clc.lua",
                    "cmd_sec.lua",
                    "cmd_cld.lua",
                    "cmd_sed.lua",
                    "cmd_cli.lua",
                    "cmd_sei.lua",
                    "cmd_clv.lua",
                    "cmd_nop.lua",
                    "cmd_rts.lua",
                    "cmd_rti.lua",
                    "cmd_brk.lua",
                    "cmd_tax.lua",
                    "cmd_txa.lua",
                    "cmd_tay.lua",
                    "cmd_tya.lua",
                    "cmd_tsx.lua",
                    "cmd_txs.lua",
                    "cmd_pla.lua",
                    "cmd_pha.lua",
                    "cmd_plp.lua",
                    "cmd_php.lua",
                    "cmd_bpl.lua",
                    "cmd_bmi.lua",
                    "cmd_bvc.lua",
                    "cmd_bvs.lua",
                    "cmd_bcc.lua",
                    "cmd_bcs.lua",
                    "cmd_bne.lua",
                    "cmd_beq.lua",
                    
                    -- Illegal Opcodes
                    "cmd_ahx.lua",
                    "cmd_aic.lua",
                    "cmd_alr.lua",
                    "cmd_axs.lua",
                    "cmd_dcp.lua",
                    "cmd_isc.lua",
                    "cmd_las.lua",
                    "cmd_lax.lua",
                    "cmd_rla.lua",
                    "cmd_rra.lua",
                    "cmd_sax.lua",
                    "cmd_shy.lua",
                    "cmd_shx.lua",
                    "cmd_slo.lua",
                    "cmd_sre.lua",
                    
                  }
                  
for k,v in pairs(commands) do
  dofile("cmd/" .. v)
  l.log("Command " .. v .. " loaded.")
  
end -- for k,v

local file = io.open(a.filename, "r")

if(not file) then
  print(a.filename)
  a.lib.write_error(01)
  os.exit()

end -- if(not file

l.log(" ---===<<< Start >>>===---")
l.log("Reading file " .. a.filename .. ".")

local lnumber = 0

-- Read the source-code.
for line in io.lines(a.filename) do
  lnumber = lnumber + 1
  table.insert(a.source, line)

end

file:close()
os.execute("clear")
-- change this in "cls" if you're in Windows

print("Welcome to the Lua-Assembler Version " .. a.version .. "." .. a.revision .. ".")
print("Compiling now " .. a.filename .. ".\n")
a.lib.print_code(a.source)

for i=1,#a.lib.parse do
  a.code = {}
  
  print("Assembling Pass " .. i)
  l.log("Assembling Pass " .. i)
  
  a.pass = i
  a.lib.parse[i]()
  
  if(not a.debug) then
      print("Pass " .. a.pass .. " finished with Errors.")
      l.log("Pass " .. a.pass .. " finished with Errors.")
      os.exit()
        
  else
      a.lib.write_error(0)
      print("Pass " .. a.pass .. " finished without Errors.\n")
      l.log("Pass " .. a.pass .. " finished without Errors.")
  end
  
  a.source = {}
  a.source = a.code 
  a.current_line = 0
  
  a.lib.print_code(a.code)
    
end -- for i=

a.lib.report()

print("\nCompiled the file to " .. a.objectname .. ".")
print("Thank you for using the assembler.")
